server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:webflux-example
    driver-class-name: org.h2.Driver
    username: sa
    password: